name: DeadlineProgress
options:
  bundleIdPrefix: dev.zphrs
  deploymentTarget:
    macOS: "26.0"
targets:
  DeadlineProgress:
    type: application
    platform: macOS
    sources: [DeadlineProgress, Icon.icon]
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: Icon
        PRODUCT_NAME: Deadline Progress Bars
        PRODUCT_BUNDLE_IDENTIFIER: dev.zphrs.DeadlineProgress
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Deadline Progress Bars
        INFOPLIST_KEY_LSUIElement: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: 7DAR7MF3X3
        CODE_SIGN_ENTITLEMENTS: DeadlineProgress/DeadlineProgress.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_VERSION: "5.0"
schemes:
  DeadlineProgress:
    build:
      targets:
        DeadlineProgress: all
    run:
      commandLineArguments: {}
